### ISSUE TITLE
Can't seem to find lekir.sql

### ISSUE THREAD

**Issue by areps** [firdauskhairuddin/lekir#2]
I wanted to try out this framework by using manual source code installation. However, I can't seem to find "lekir.sql" in the directory and the documentation. Thank you.

**Comment by firdauskhairuddin** [comment]
> I wanted to try out this framework by using manual source code installation. However, I can't seem to find "lekir.sql" in the directory and the documentation. Thank you.

My bad, i forgot to push the sql in the github. enjoy now!
